package com.opkey.web.enums;

public enum VisibilityKeywords {
	VerifyObjectVisible,
	VerifyImageNotVisible,
	VerifyImageVisible,
	GetObjectVisibility,
	VerifyEditBoxExist,
	VerifyEditBoxnotExist,
	VerifyTextAreaExist,
	VerifyTextAreanotExist,
	VerifyObjectExists,
	VerifyDropDownItemExists,
	VerifyEditBoxNotExist,
	VerifyButtonExist,
	VerifyTextAreaNotExist,
	VerifyObjectDoesNotExists,
	VerifyLinkExist,
	VerifyAllLinkExist,
	VerifyImageExist,
	VerifyRadioButtonExist,
	VerifyCheckBoxExist,
	VerifyDropDownExist,
	VerifyAllDropDownItemExist,
	VerifyMultipleDropDownItemExist,
	VerifyEditBoxExistAndWait,
	Web_VerifyListItemExists,
}
